[platformio]
description = HC32F460 grblHAL driver
include_dir = Inc
src_dir = Src
boards_dir = platformio_boards
default_envs = hc32f460_voxelab_aquila_v102
extra_configs = platformio.local.ini

[env]
platform = ststm32
board = genericHC32F460
framework =
lib_archive = no
build_unflags =
  -Os
build_flags =
  -I .
  -I Inc
  -I boards
  -I grbl
  -I SDK/main
  -I SDK/main/hdsc32core/common
  -I SDK/main/hdsc32core/Include
  -I SDK/drivers/library/inc
  -D HC32F46x
  -D HC32F460
  -D __HC32F460__
  -D __FPU_PRESENT=1
  -include Inc/my_machine.h
  -D N_SPINDLE=2
  -D ADAPTIVE_MULTI_AXIS_STEP_SMOOTHING=0
  -std=gnu11
  -O2
  -g3
  -ffunction-sections
  -fdata-sections
  -fno-common
  -Wall
  -Wextra
  -Wno-unused-parameter
  -Wno-missing-field-initializers
board_build.ldscript = ldscripts/hc32f46x_flash.ld
extra_scripts =
  pre:scripts/platformio_pre.py
  post:scripts/platformio_post.py
upload_protocol = custom
upload_command = pyocd load $SOURCE -t hc32f460 -a 0xC000

[env:hc32f460_voxelab_aquila_v102]
build_flags =
  ${env.build_flags}

[env:hc32f460_my_machine]
build_flags =
  ${env.build_flags}
  -D BOARD_MY_MACHINE
